export const GLinks: Record<string, string> = {
  BaseStyleProps: 'https://g.antv.antgroup.com/api/basic/display-object#%E7%BB%98%E5%9B%BE%E5%B1%9E%E6%80%A7',
  DisplayObject: 'https://g.antv.antgroup.com/api/basic/display-object',
  GroupStyleProps: 'https://g.antv.antgroup.com/api/basic/group',
  TextStyleProps: 'https://g.antv.antgroup.com/api/basic/text',
  CircleStyleProps: 'https://g.antv.antgroup.com/api/basic/circle',
  EllipseStyleProps: 'https://g.antv.antgroup.com/api/basic/ellipse',
  RectStyleProps: 'https://g.antv.antgroup.com/api/basic/rect',
  ImageStyleProps: 'https://g.antv.antgroup.com/api/basic/image',
  LineStyleProps: 'https://g.antv.antgroup.com/api/basic/line',
  PolygonStyleProps: 'https://g.antv.antgroup.com/api/basic/polygon',
  PolylineStyleProps: 'https://g.antv.antgroup.com/api/basic/polyline',
  PathStyleProps: 'https://g.antv.antgroup.com/api/basic/path',
  HTMLStyleProps: 'https://g.antv.antgroup.com/api/basic/html',
};
