export const PageTitle: Record<string, string[]> = {
  // behaviors
  BaseBehavior: ['BaseBehavior', '基础交互'],
  BrushSelect: ['BrushSelect', '框选'],
  ClickElement: ['ClickElement', '点击选中'],
  CollapseExpand: ['CollapseExpand', '展开折叠Combo'],
  CreateEdge: ['CreateEdge', '创建边'],
  DragCanvas: ['DragCanvas', '拖拽画布'],
  DragElement: ['DragElement', '拖拽元素'],
  DragElementForce: ['DragElementForce', '力导向拖拽元素'],
  FocusElement: ['FocusElement', '聚焦元素'],
  HoverElement: ['HoverElement', '悬停激活'],
  LassoSelect: ['LassoSelect', '套索选择'],
  ZoomCanvas: ['ZoomCanvas', '缩放画布'],
  // plugins
  BubbleSets: ['BubbleSets', '气泡集'],
  CameraSetting: ['CameraSetting', '相机设置'],
  ContextMenu: ['ContextMenu', '右键菜单'],
  GridLine: ['GridLine', '网格线'],
  History: ['History', '历史记录'],
  Hull: ['Hull', '轮廓包围'],
  Legend: ['Legend', '图例'],
  Toolbar: ['Toolbar', '工具栏'],
  Tooltip: ['Tooltip', '提示框'],
  Watermark: ['Watermark', '水印'],
};
