name: 'Issue Hunt 计划'
description: 创建一个新的 issue，如果你的 issue 不符合规范，它将会被自动关闭。
body:
  - type: checkboxes
    id: issue_hunt_program
    attributes:
      label: Issue Hunt 计划（可选）
      description: |
        Issue Hunt 计划是 AntV 为了鼓励社区贡献者参与到 AntV 项目中来，提出的一个激励计划。如果想了解更多，可以查看 [Issue Hunt 计划](https://github.com/antvis/G6/blob/master/ISSUEHUNT.md)
        通过 Issue Hunt 计划提出的 issue 与普通 issue 无异。普通 issue 也可加入 Issue Hunt 计划，但需要经过 AntV 团队审核。
      options:
        - label: 我同意将这个 Issue 参与 Issue Hunt 计划
    validations:
      required: false
  - type: dropdown
    id: issue_hunt_difficulty
    attributes:
      label: Issue 难度
      options:
        - 低难度
        - 中等难度
        - 高难度
    validations:
      required: false
  - type: textarea
    id: bounty_description
    attributes:
      label: 悬赏
      description: | 
        如果您非项目维护者，并愿意对该 issue 悬赏，可以在此处提供悬赏描述，并在提交 Issue 后在 [IssueHunt](https://oss.issuehunt.io/r/antvis/G6/issues) 提供悬赏金额。
        平台可能会收取一定的手续费，这与 AntV 无关。
      placeholder: |
        例如：如果您能够在 24 小时内解决此问题，我将支付 $100。
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        在提交新 issue 之前，先通过以下链接查看有没有类似的 bug 或者建议:
         - [G6 Issues](https://github.com/antvis/G6/issues)
         - [G6 Closed Issues](https://github.com/antvis/G6/issues?q=is%3Aissue+is%3Aclosed)
         - [G6 Discussions](https://github.com/antvis/G6/discussions)
  - type: textarea
    id: description
    attributes:
      label: 问题描述
      description: 简洁清晰地描述你遇到的问题。
    validations:
      required: true
  - type: input
    id: link
    attributes:
      label: 重现链接
      description: |
        可以使用 CodeSandbox(https://codesandbox.io/s/new) 或者 StackBlitz(https://stackblitz.com/) 重现你的问题。
      placeholder: |
        示例: CodeSandBox 或者 StackBlitz URL
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: 重现步骤
      description: 简洁清晰的重现步骤能够帮助我们更迅速地定位问题所在。
      placeholder: |
        1.进入页面...
        2.点击....
        3.查看错误....
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: 预期行为
      description: 描述你期望的结果以及实际的结果。
      placeholder: |
        我期望看到...，但我看到了...
    validations:
      required: true
  - type: textarea
    id: platform
    attributes:
      label: 平台
      value: |
        - 操作系统: [macOS, Windows, Linux, React Native ...]
        - 网页浏览器: [Google Chrome, Safari, Firefox]
        - G6 版本: [4.5.1 ... ]
    validations:
      required: true
  - type: textarea
    id: screenshots_or_videos
    attributes:
      label: 屏幕截图或视频（可选）
      description: 可以添加屏幕截图或视频帮助你解释问题。
      placeholder: |
        可以将你的图片或者视频拖拽到此处↓
  - type: textarea
    id: additional
    attributes:
      label: 补充说明（可选）
      description: 比如：遇到这个 bug 的业务场景、上下文。