declare const _default: {
    getDefaultCfg(): object;
    getEvents(): {
        click?: string;
        mousedown?: string;
        mouseup?: string;
        dblclick?: string;
        contextmenu?: string;
        mouseenter?: string;
        mouseout?: string;
        mouseover?: string;
        mousemove?: string;
        mouseleave?: string;
        dragstart?: string;
        dragend?: string;
        drag?: string;
        dragenter?: string;
        dragleave?: string;
        drop?: string;
        keyup?: string;
        keydown?: string;
        wheel?: string;
        "node:click"?: string;
        "node:contextmenu"?: string;
        "node:dblclick"?: string;
        "node:dragstart"?: string;
        "node:drag"?: string;
        "node:dragend"?: string;
        "node:mouseenter"?: string;
        "node:mouseleave"?: string;
        "node:mousemove"?: string;
        "edge:click"?: string;
        "edge:contextmenu"?: string;
        "edge:dblclick"?: string;
        "edge:mouseenter"?: string;
        "edge:mouseleave"?: string;
        "edge:mousemove"?: string;
        "canvas:mousedown"?: string;
        "canvas:mousemove"?: string;
        "canvas:mouseup"?: string;
        "canvas:click"?: string;
        "canvas:mouseleave"?: string;
    };
} & {
    onMouseEnter(e: import("../../types").IG6GraphEvent): void;
    onMouseMove(e: import("../../types").IG6GraphEvent): void;
    onMouseLeave(e: import("../../types").IG6GraphEvent): void;
    showTooltip(e: import("../../types").IG6GraphEvent): void;
    hideTooltip(): void;
    updatePosition(e: import("../../types").IG6GraphEvent): void;
    _createTooltip(canvas: any): HTMLElement;
};
export default _default;
